### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by kristofferdarj** [gourmet/knp-menu#3]
I get the following when trying to install via composer:

Problem 1
    - Can only install one of: cakephp/cakephp[3.0.x-dev, 3.0.7].
    - Can only install one of: cakephp/cakephp[3.0.x-dev, 3.0.7].
    - Can only install one of: cakephp/cakephp[3.0.x-dev, 3.0.7].
    - gourmet/knp-menu v0.4.0 requires cakephp/cakephp 3.0.*-dev -> satisfiable by cakephp/cakephp[3.0.x-dev].
    - Installation request for gourmet/knp-menu ~0.4 -> satisfiable by gourmet/knp-menu[v0.4.0].
    - Installation request for cakephp/cakephp == 3.0.7.0 -> satisfiable by cakephp/cakephp[3.0.7].

The require line in my composer is from the standard cake install and reads:
"cakephp/cakephp": "~3.0",

**Comment by jadb** [comment]
That's because you were trying to get the last tagged release (which was old). I just tagged a new release but suggest you use `dev-master` in composer for this plugin until it's `1.0` version is released.
